spring:
  application:
    name: btg-challenge-api
  
  data:
    mongodb:
      auto-index-creation: true
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASS:senha123}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_DATABASE:btgpactualdb}?authSource=admin
  
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:admin}
    password: ${RABBIT_PASS:123456}
    
logging:
  level:
    root: INFO
    org.springframework.data.mongodb: INFO
    tech.buildrun.btgpactual: INFO

server:
  port: 8080

